<?php
$title = 'Мои книги';
$this->headTitle($title);
?>

<h1>Мой список книг</h1>
<p>
    <a href="<?php echo $this->url('book', array('action'=>'add'));?>">добавить новую книгу</a>
</p>

<table class="table">
    <tr>
        <th>Название</th>
        <th>Автор</th>
        <th></th>
    </tr>
    <?php foreach ($books as $book): ?>
        <tr>
            <td><?php echo $this->escapeHtml($book->title); ?></td>
            <td><?php echo $this->escapeHtml($book->author); ?></td>
            <td>
                <a href="<?php echo $this->url('book',
                    array('action' => 'edit', 'id' => $book->id)); ?>">Edit</a>
                <a href="<?php echo $this->url('book',
                    array('action' => 'delete', 'id' => $book->id)); ?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>